# Generated by Django 4.2.6 on 2023-11-04 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutHome', '0003_alter_setvolume_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setvolume',
            name='date',
            field=models.TimeField(default=datetime.date.today),
        ),
    ]
