# Generated by Django 4.2.6 on 2023-11-04 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutHome', '0004_alter_setvolume_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setvolume',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
